pull_request_rules:
  - name: Master automatic merge
    conditions:
      - "#approved-reviews-by>=3"
      - base=master
    actions:
      merge:
        method: merge
  - name: Develop automatic merge
    conditions:
      - "#approved-reviews-by>=1"
      - base=develop
    actions:
      merge:
        method: merge
      delete_head_branch: {}