language: go

go:
  - 1.12.x

notifications:
  email: false

services:
  - docker

env:
  global:
    - JJ_MARIADBUSER=root
    - JJ_MARIADBPWD=123456
    - GOFLAGS=-mod=vendor
    - GO111MODULE=on

before_install:
  - docker pull mariadb
  - docker run -d --net=host -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=sjtujj mariadb

install:
  - wget https://releases.hashicorp.com/consul/1.5.2/consul_1.5.2_linux_amd64.zip
  - unzip consul_1.5.2_linux_amd64.zip
  - sudo mv consul /usr/local/bin/
  - go get github.com/mattn/goveralls github.com/modocache/gover

before_script:
  - consul agent  -bootstrap -server -data-dir=./data/ 2>&1 1>consul.log &
  - sleep 3
  - cd backend

script:
  - consul kv import @consul.json
  - go list -f '{{if len .TestGoFiles}}"s=`echo {{.Dir}} | tail -c 6` && [ $s == "utils" ] && go test -tags=test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}} || go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -L 1 sh -c
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN