language: go

go:
  - 1.12.x

notifications:
  email: false

services:
  - docker

env:
  global:
    - JJ_MARIADBUSER=root
    - JJ_MARIADBPWD=123456
    - JJ_MONGODBUSER=root
    - JJ_MONGODBPWD=123456

before_install:
  - sudo /etc/init.d/mysql stop
  - docker pull mariadb
  - docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=sjtujj mariadb
  - docker pull mongo
  - docker run -d -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=123456 mongo

install:
  - wget https://releases.hashicorp.com/consul/1.5.2/consul_1.5.2_linux_amd64.zip
  - unzip consul_1.5.2_linux_amd64.zip
  - sudo mv consul /usr/local/bin/
  - go get github.com/mattn/goveralls github.com/modocache/gover
  - export GOFLAGS=-mod=vendor
  - export GO111MODULE=on

before_script:
  - consul agent  -bootstrap -server -bind=127.0.0.1 -data-dir=./data/ 2>&1 1>consul.log &
  - sleep 3
  - cd backend

script:
  - consul kv import @consul.json
  - go list -f '{{if len .TestGoFiles}}"s=`echo {{.Dir}} | tail -c 6` && [ $s == "utils" ] && go test -tags=test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}} || go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -L 1 bash -c
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  - docker-compose build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cp config_deploy.json config.json

deploy:
  provider: script
  script: bash dockerpush.sh
  on:
    branch: master