settings:
  files:
    outputs:
      status: false
      name: outputs.log
    logs:
      status: false
      name: logs.log
    errors:
      status: false
      name: errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 5002
  host: localhost
schema:
- name: api-auth
  path: api/auth
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: apidoc
      type: after
      path: ../../
      output: true
- name: api-user
  path: api/user
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
      - command: apidoc
        type: after
        path: ../../
        output: true
- name: api-sellinfo
  path: api/sellinfo
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
      - command: apidoc
        type: after
        path: ../../
        output: true
- name: srv-auth
  path: srv/auth
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: bash generate.sh
      type: before
      path: ../../
      output: true
    - command: apidoc
      type: after
      path: ../../
      output: true
- name: srv-user
  path: srv/user
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: bash generate.sh
      type: before
      path: ../../
      output: true
    - command: apidoc
      type: after
      path: ../../
      output: true
- name: srv-sellinfo
  path: srv/sellinfo
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - proto
      - go
    paths:
      - /
      - ../../utils
    scripts:
      - command: bash generate.sh
        type: before
        path: ../../
        output: true
      - command: apidoc
        type: after
        path: ../../
        output: true